### ISSUE TITLE
The console panel doesn't have a flat appearance compared to the rest

### ISSUE THREAD

**Issue by stephen147** [reupen/console_panel#1]
See attached the UI of where I'm referring: (not the same sunken appearance)

![image](https://user-images.githubusercontent.com/14054664/72655592-7be50500-398d-11ea-96e7-81fc63a49e03.png)

The relevant settings I have are here:
![image](https://user-images.githubusercontent.com/14054664/72655616-961ee300-398d-11ea-945c-16eaff51eb77.png)

**Comment by reupen** [comment]
Hi,

The built-in panels used to default to the 'sunken' style, but they were changed to the flat style a few versions ago.

Console panel doesn't have any settings to change the edge style it seems. I'll update to default to the flat style, and make the setting configurable.

Thanks

**Comment by stephen147** [comment]
Thanks, look forward to the fix.

**Comment by stephen147** [comment]
Is there a specific setting (can't find one) for the console because the console box has the same appearance in version:

**Columns UI 1.4.0-rc.1**

**Comment by reupen** [comment]
You'll need to update Console panel to version 1.0.0, and then right-click on the panel and change the edge style to None.

**Comment by stephen147** [comment]
Oh, I was on v0.5 and the updates weren't pushed out when I clicked check for updates.

Thanks for the fix!
