### ISSUE TITLE
Possibility to write log files

### ISSUE THREAD

**Issue by regorxxx** [reupen/console_panel#9]
DUI allows to save log to a file, but the option gets reset everytime foobar is restarted.
It would be great to have the possibility to write log files without having the option reset on every startup. 

The rationale was that crash reports are already saved to other place (1), and logs could get bigger and bigger (2).... but (1) does not apply at all when there are tons of components writing other useful things to console (for example Spider Monkey Panel), (2) is not a real problem (since may programs have permanent logging to file...) and (2) could be solved by blanking log file on restart(*).

(*) Logs could then be moved\renamed with external scripts if required after closing foobar.

Apart from the obvious use-cases for everybody, I'm currently working on an updated online controller using the existing tools (foo http control and SMP). Logs are not exposed in any way, but the log file. So having the option to always save logs to a file allows to send the log to the server and read it on the controller point. Being able to read the logs at any place (and not only the Server PC) greatly expands its debugging capabilities and logging other info (for example many SMP scripts log useful info to console, and you could see the result of SMP scripts called by the controller on the log).

**Comment by reupen** [comment]
Although the Default UI console UI element has logging, I'm not convinced that persistent logging really belongs in this panel. 

If someone wanted to enable persistent logging, they shouldn't be forced to insert this panel into their layout. Additionally, having the panel write a log file when it isn't in a layout may also be confusing.

I think it'd be better implemented as a separate component (or even in the foobar2000 core itself), with the functionality probably accessed from somewhere like Preferences.

**Comment by regorxxx** [comment]
Neither Peter nor anyone has been interested on adding the functionality, although it's something requested along the years. 

But can't argue with that. You are totally right, it makes more sense in the core or as sep. component.
